"""add document versioning

Revision ID: aa6f86b1fe15
Revises: ba6c57777ad9
Create Date: 2026-06-25 08:59:07.759000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa6f86b1fe15'
down_revision: Union[str, None] = 'ba6c57777ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('parent_document_id', sa.UUID(), nullable=True))
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'documents', 'documents', ['parent_document_id'], ['id'])
    op.drop_column('documents', 'chunk_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('documents', 'parent_document_id')
    op.drop_column('documents', 'version')
    # ### end Alembic commands ###