"""add subscriptions table

Revision ID: ba6c57777ad9
Revises: ba8ab1d839cf
Create Date: 2026-06-25 08:46:52.512703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba6c57777ad9'
down_revision: Union[str, None] = 'ba8ab1d839cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###