"""increase file_type column length

Revision ID: ed825afe0cad
Revises: ae4c4cc7e5a3
Create Date: 2026-06-24 12:26:16.584504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed825afe0cad'
down_revision: Union[str, None] = 'ae4c4cc7e5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###