"""add document versioning

Revision ID: f277f1a007dc
Revises: aa6f86b1fe15
Create Date: 2026-06-25 09:08:46.131955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f277f1a007dc'
down_revision: Union[str, None] = 'aa6f86b1fe15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###